export default interface Game {      
    gameId: number,
    homeColour: string,
    homeTeamLogo: string,
    homeTeamName: string,
    p1home: number,
    p1visitor: number,
    p2home: number,
    p2visitor: number,
    p3home: number,
    p3visitor: number,
    p4home: number,
    p4visitor: number,
    p5home: number,
    p5visitor: number,
    risultato: string,
    start: string,
    visitorTeamLogo: string,
    visitorTeamName: string,
    visitorsColour: string,
}